#!/bin/bash
VERSION=$(date +%Y%m%d)
FILE=TitanPrimeROM-UNOFFICIAL-${VERSION}.zip
./tools/compile_apps_linux
rm -rf TitanPrimeROM-UNOFFICIAL-*.zip
7za a -mx9 -xr@tools/exclusion.txt "$FILE" META-INF system supersu file_contexts logo.bin boot.img
cd ..